config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      patch :increase_stock
      patch :decrease_stock
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: {greater_than: 0}
  validates :quantity, numericality: {greater_than_or_equal_to: 0}

  has_one_attached :image

  # search logic
  def self.search(name)
    if name.present?
      search_term = "%#{name.downcase}%"
      where("lower(name) LIKE ?", search_term)
    else
      order(created_at: :desc)
    end
  end

  # low stock logic
  def self.low_stock
    where("quantity <= ?", 10)
  end

  # increase stock
  def increase_stock(amount = 1)
    increment!(:quantity, amount.to_i)
  end

  def decrease_stock(amount = 1)
    decrement!(:quantity, amount.to_i)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy increase_stock decrease_stock]

  # GET /products or /products.json
  def index
    @products = Product.search(params[:name])
    @low_stock_products = Product.low_stock

    if @low_stock_products.present?
      low_stock_names = @low_stock_products.map(&:name).join(", ")
      flash.now[:notice] = "#{low_stock_names} #{"are" if @low_stock_products.count > 1} low on stock"
    end

    @product = Product.new

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # stock increase and decrease
  def increase_stock
    @product.increase_stock(params[:amount])
    respond_to do |format|
      format.html { redirect_to products_url }
      format.turbo_stream
    end
  end

  def decrease_stock
    @product.decrease_stock(params[:amount])
    respond_to do |format|
      format.html { redirect_to products_url }
      format.turbo_stream
    end
  end

  def update_stock
    if product.quantity <= 10
      low_stock_notification(product)
    end
  end

  # notifications display
  def low_stock_notification
    product = Product.find(params[:id])
    Turbo::StreamsChannel.broadcast_replace_to(
      "product_notifications",
      target: "low_stock_notification_#{product.id}",
      partial: "products/notification",
      locals: {product: product}
    )
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def low_stock_class(product)
    (product.quantity <= 10) ? "bg-warning text-dark" : ""
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# bootstrp cdn %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex flex-wrap">
    <div class="form-group mb-2 mr-2">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group mb-2 mr-2">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group mb-2 mr-2">
      <%= form.label :price, class: "form-label" %>
      <%= form.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group mb-2 mr-2">
      <%= form.label :quantity, class: "form-label" %>
      <%= form.number_field :quantity, class: "form-control" %>
    </div>

    <div class="form-group mb-2 mr-2">
      <%= form.label :image, class: "form-label" %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group mb-2">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="product_<%= product.id %>">
  <h2><%= product.name %></h2>
  <% if product.image.attached? %>
    <p><%= image_tag(product.image, class: 'img-thumbnail', style: "width: 200px; height: 200px;") %></p>
  <% else %>
    <p class="badge text-bg-danger">No image available</p>
  <% end %>
  <p><%= product.description %></p>
  <p>Price: $<%= product.price %></p>
  <p>Stock Level: <%= product.quantity %></p>
  <%= link_to 'Increase Stock', increase_stock_product_path(product, amount: 1), method: :patch, class: 'btn btn-success', data: { turbo_method: :patch } %>
  <%= link_to 'Decrease Stock', decrease_stock_product_path(product, amount: 1), method: :patch, class: 'btn btn-danger', data: { turbo_method: :patch } %>
  <%= link_to 'All Products', products_path, class: 'btn btn-primary' %>
</div>

app/views/products/decrease_stock.turbo_stream.erb
<%= turbo_stream.replace dom_id(@product) do %>
  <%= render @product %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/increase_stock.turbo_stream.erb
<%= turbo_stream.replace dom_id(@product) do %>
  <%= render @product %>
<% end %>

app/views/products/index.html.erb
<p class="badge text-bg-warning"><%= notice %></p>
<h1>Add New Product</h1>
<div class="mb-4">
  <%= render "form", product: @product %>
</div>
<hr />
<%# display products as table %>
<h1>Products</h1>
<%= form_with url: products_path, class: "search-form", method: :get do |form| %>
  <div class="input-group">
    <%= form.text_field :name, value: params[:name], class: "form-control", placeholder: "Search for product by name" %>
    <div class="input-group-append">
      <%= form.submit "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<br />

<table class="table table-bordered" data-controller="products">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price (KES)</th>
      <th>Quantity (Stock Level)</th>
      <th>Image</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <% if product.quantity <= 10 %>
            (<%= product.quantity %>)&nbsp;
            <span class="badge text-bg-danger">Low Stock</span>
          <% else %>
            (<%= product.quantity %>)&nbsp;
            <span class="badge text-bg-success">Normal Stock</span>
          <% end %>
        </td>
        <td>
          <% if product.image.attached? %>
            <p><%= image_tag(product.image, class: 'img-thumbnail', style: "width: 100px; height: 100px;") %></p>
          <% else %>
            <p class="badge text-bg-danger">No image available</p>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", product_path(product), class: 'btn btn-success' %>
          <%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %>
          <%= link_to "Delete", product_path(product), method: :delete, data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/index.turbo_stream.erb
<%= turbo_stream.replace "products" do %>
  <%= render partial: "products/products", locals: { products: @products } %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to Products", products_path, class: "btn btn-secondary" %>
</div>

app/views/products/show.html.erb
<%= turbo_frame_tag dom_id(@product) do %>
  <%= render @product %>
<% end %>